"""Le vocabulaire accentue du site, en supplement de scripts/accentuer.py.

Tire des mots reellement presents dans les pages, releves un par un. Deux regles
ont guide les choix, et elles expliquent les absences :

  AMBIGU, DONC ABSENT. Une forme en -e peut etre un verbe conjugue sans accent
  final ou un participe avec — « le script decoupe » contre « un historique
  decoupe ». Quand le doute existe, le mot est ecrit avec les accents de son
  DEBUT seulement (« découpe »), ce qui est juste dans les deux cas, ou bien il
  est laisse de cote.

  JAMAIS DE REGLE QUI DEVINE. Les formes flechies sont listees a la main. Une
  regle qui ajoute un accent « quand ca ressemble a » finit toujours par ecrire
  « qui à le mieux rendu ».

  LE SUPPLEMENT AJOUTE, IL NE CORRIGE PAS. Il ecrasait seize entrees du noyau, et
  neuf d'entre elles etaient des gardes deliberes — le noyau y ecrivait le mot
  IDENTIQUE a lui-meme, ce qui veut dire « ne pas y toucher, c'est ambigu ». Le
  supplement les remplacait par le participe, en silence, et personne ne pouvait
  le voir : espace -> espacé, publie -> publié, utilise -> utilisé, signale ->
  signalé, supprime -> supprimé, explique -> expliqué, immobilise -> immobilisé,
  invalide -> invalidé, resserre -> resserré. Plus sept renversements de sens :
  repères (les points de comparaison) devenait repérés, résume devenait résumé,
  vérifie devenait vérifié. accentuer.py refuse desormais de demarrer si un seul
  mot du supplement contredit le noyau.

  TROIS ENTREES EN PLUS ONT ETE RETIREES — engage, rejoue, corrige — parce
  qu'elles produisaient, mesure a l'appui, trois fautes dans les pages :
  « Ce bot engage donc plus d'argent » -> « engagé », « l'epreuve rejoue le meme
  reglage » -> « rejoué », « ce que cette etude ne corrige pas » -> « corrigé ».
  Aucune n'etait un participe. Elles etaient la depuis assez longtemps pour que
  la prochaine execution de l'outil publie les trois d'un coup.
"""

SUPPLEMENT = {
    #  --- releves dans le journal apres le nettoyage du dictionnaire ---
    #  Tous sans ambiguite possible : ni verbe conjugue, ni double lecture.
    "ecrit": "écrit", "ecrits": "écrits", "ecrite": "écrite", "ecrites": "écrites",
    "echec": "échec", "echecs": "échecs", "etant": "étant",
    "entierement": "entièrement", "ecran": "écran", "ecrans": "écrans",
    "etroit": "étroit", "etroite": "étroite", "etroites": "étroites",
    "etape": "étape", "etapes": "étapes",
    "etendue": "étendue", "etendues": "étendues",
    # --- le marche, les prix ---
    "marche": "marché", "marches": "marchés",
    "cloture": "clôture", "clotures": "clôtures", "cloturee": "clôturée",
    "haussiere": "haussière", "baissiere": "baissière",
    "meche": "mèche", "meches": "mèches",
    "reticule": "réticule",
    "graduee": "graduée", "gradues": "gradués", "graduation": "graduation",
    "densite": "densité",
    "echange": "échange", "echanges": "échanges", "echangent": "échangent",
    "echangee": "échangée", "echangees": "échangées",
    "telephone": "téléphone",

    # --- l'etat des choses ---
    "reel": "réel", "reels": "réels", "reelle": "réelle", "reelles": "réelles",
    "reellement": "réellement",
    "etait": "était", "etaient": "étaient", "etais": "étais",
    "etabli": "établi", "etablis": "établis", "etablie": "établie",
    "etablies": "établies", "etablir": "établir", "etablit": "établit",
    "honnete": "honnête", "honnetes": "honnêtes", "honnetement": "honnêtement",
    "tete": "tête", "tetes": "têtes",
    "coeur": "cœur", "oeil": "œil", "oeuvre": "œuvre",
    "extreme": "extrême", "extremes": "extrêmes", "extremite": "extrémité",
    "extremites": "extrémités",
    "egal": "égal", "egale": "égale", "egales": "égales", "egaux": "égaux",
    "egalement": "également", "egalite": "égalité",
    "complete": "complète", "completes": "complètes", "completee": "complétée",
    "completement": "complètement", "completer": "compléter",
    "palmares": "palmarès",
    "succession": "succession", "successifs": "successifs",
    "recent": "récent", "recents": "récents", "recente": "récente",
    "recentes": "récentes", "recemment": "récemment",
    "decennie": "décennie", "decennies": "décennies",
    "eternel": "éternel", "eternelle": "éternelle",
    "ideal": "idéal", "ideale": "idéale", "ideaux": "idéaux",
    "arithmetique": "arithmétique",
    "correlation": "corrélation", "correlations": "corrélations",
    "equidistant": "équidistant", "equidistants": "équidistants",
    "equidistantes": "équidistantes",
    "implementation": "implémentation", "implementations": "implémentations",
    "creation": "création", "creations": "créations",
    "uniformement": "uniformément", "uniforme": "uniforme",

    # --- participes feminins et pluriels, non ambigus ---
    "posee": "posée", "posees": "posées", "poses": "posés",
    "dessinee": "dessinée", "dessinees": "dessinées", "dessines": "dessinés",
    "achetee": "achetée", "achetees": "achetées", "achetes": "achetés",
    "engagee": "engagée", "engagees": "engagées", "engages": "engagés",
    "figee": "figée", "figees": "figées", "figes": "figés",
    "corrigee": "corrigée", "corrigees": "corrigées", "corriges": "corrigés",
    "trouvee": "trouvée", "trouvees": "trouvées", "trouves": "trouvés",
    "datee": "datée", "datees": "datées",
    "fabriquee": "fabriquée", "fabriquees": "fabriquées",
    "reperee": "repérée", "reperees": "repérées",     "supposee": "supposée", "supposees": "supposées", "supposes": "supposés",
    "chargee": "chargée", "chargees": "chargées", "charges": "chargés",
    "menee": "menée", "menees": "menées", "menes": "menés",
    "passee": "passée", "passees": "passées", "passes": "passés",
    "decoupee": "découpée", "decoupees": "découpées",
    "agregee": "agrégée", "agregees": "agrégées", "agreges": "agrégés",
    "recopiee": "recopiée", "recopiees": "recopiées",
    "cumulee": "cumulée", "cumulees": "cumulées", "cumules": "cumulés",
    "designee": "désignée", "designees": "désignées", "designes": "désignés",
    "testee": "testée", "testees": "testées", "testes": "testés",
    "rangee": "rangée", "rangees": "rangées", "ranges": "rangés",
    "debarrassee": "débarrassée", "debarrasse": "débarrassé",
    "simulee": "simulée", "simulees": "simulées", "simules": "simulés",
    "etiree": "étirée", "etirees": "étirées", "etires": "étirés",
    "moitie": "moitié", "moities": "moitiés",

    # --- prefixes toujours accentues : de-, re-, pre-, e- ---
    "declenchent": "déclenchent", "declenchant": "déclenchant",
    "decrit": "décrit", "decrite": "décrite", "decrits": "décrits",
    "decrites": "décrites", "decrire": "décrire",
    "deduire": "déduire", "deduit": "déduit", "deduite": "déduite",
    "definir": "définir", "definit": "définit", "definition": "définition",
    "definitions": "définitions", "defini": "défini", "definie": "définie",
    "definis": "définis", "definies": "définies",
    "degrade": "dégradé", "degradee": "dégradée",
    "demande": "demande", "demarre": "démarré", "demarrer": "démarrer",
    "demarrage": "démarrage",
    "depend": "dépend", "dependent": "dépendent", "dependre": "dépendre",
    "dependance": "dépendance",
    "depuis": "depuis",
    "derive": "dérive", "derives": "dérivés", "deriver": "dériver",
    "descend": "descend", "descendu": "descendu", "descendue": "descendue",
    "detache": "détache", "detachent": "détachent",
    "detruit": "détruit", "detruite": "détruite", "detruire": "détruire",
    "developpe": "développe", "developpement": "développement",
    "ecrase": "écrase", "ecrasent": "écrasent", "ecraseraient": "écraseraient",
    "ecraser": "écraser",
    "editorial": "éditorial",
    "elimine": "élimine", "eliminent": "éliminent",
    "eloigne": "éloigne", "eloignee": "éloignée",
    "emet": "émet", "emis": "émis",
    "enonce": "énoncé", "enoncer": "énoncer",
    "epaisseur": "épaisseur", "epaisseurs": "épaisseurs", "epais": "épais",
    "epaisse": "épaisse",
    "equilibre": "équilibre", "equivalent": "équivalent",
    "etage": "étage", "etages": "étages",
    "etirer": "étirer", "etire": "étire",
    "evalue": "évalue", "evaluer": "évaluer", "evaluation": "évaluation",
    "eventuel": "éventuel", "eventuelle": "éventuelle", "eventuellement": "éventuellement",
    "precise": "précise", "precisions": "précisions",
    "predit": "prédit", "prediction": "prédiction",
    "prelevement": "prélèvement", "preleve": "prélève",
    "premier": "premier", "prend": "prend",
    "reagit": "réagit",
    "recuperation": "récupération", "recupere": "récupère",
    "redonne": "redonne", "reduire": "réduire", "reduit": "réduit",
    "reduite": "réduite", "reduction": "réduction",
    "reecrit": "réécrit", "reecrire": "réécrire", "reecriture": "réécriture",
    "refait": "refait", "refaire": "refaire",
    "regenere": "régénère", "regenerer": "régénérer",
    "reglerait": "réglerait", "reglent": "règlent", "reglera": "réglera",
    "remonte": "remonte", "remontee": "remontée", "remonter": "remonter",
    "repond": "répond", "repondent": "répondent", "repondu": "répondu",
    "repete": "répète", "repeter": "répéter", "repetition": "répétition",
    "resiste": "résiste", "resistance": "résistance", "resistances": "résistances",
    "resout": "résout", "resoudre": "résoudre",
    "respecte": "respecte",
    "retablir": "rétablir",
    "reussi": "réussi", "reussie": "réussie", "reussies": "réussies",
    "reussit": "réussit", "reussite": "réussite",
    "revele": "révèle", "revelent": "révèlent", "revelation": "révélation",
    "severite": "sévérité",
    "vérifiant": "vérifiant", "verifiant": "vérifiant",

    # --- divers du vocabulaire du banc ---
    "cle": "clé", "cles": "clés",
    "duree": "durée", "durees": "durées",
    "entree": "entrée", "entrees": "entrées",
    "sortie": "sortie", "sorties": "sorties",
    "releve": "relevé", "releves": "relevés",
        "schema": "schéma", "schemas": "schémas",
    "serieux": "sérieux", "serieuse": "sérieuse",
    "somme": "somme",
    "theoriquement": "théoriquement",
    "visee": "visée", "visees": "visées",
    "cree": "créé", "creee": "créée", "crees": "créés", "creer": "créer",
    "considere": "considère", "considerer": "considérer",
    "espere": "espère", "esperer": "espérer",
    "gere": "gère", "gerer": "gérer",
    "l'ecart": "l'écart", "l'echelle": "l'échelle", "l'etat": "l'état",
    "l'epreuve": "l'épreuve", "l'etude": "l'étude", "l'ecran": "l'écran",
    "l'entree": "l'entrée", "l'etiquette": "l'étiquette", "l'evenement": "l'événement",
    "l'experience": "l'expérience", "l'echange": "l'échange",
    "d'ecart": "d'écart", "d'echelle": "d'échelle", "d'etude": "d'étude",
    "d'etre": "d'être", "d'eviter": "d'éviter", "d'epreuve": "d'épreuve",
    "qu'echelle": "qu'échelle",
    "rafraichit": "rafraîchit", "rafraichir": "rafraîchir",
    "boite": "boîte", "boites": "boîtes",
    "connait": "connaît", "connaitre": "connaître", "connaissent": "connaissent",
    "parait": "paraît", "paraitre": "paraître",
    "maitrise": "maîtrise", "maitriser": "maîtriser",
    "aout": "août",
    "ca": "ça",
    "gout": "goût", "gouts": "goûts",
    "surete": "sûreté",
    # --- derniers releves a la lecture ---
    "recoit": "reçoit", "recoivent": "reçoivent", "recu": "reçu", "recue": "reçue",
    "recus": "reçus", "recues": "reçues", "recevoir": "recevoir",
    "apercoit": "aperçoit", "apercu": "aperçu",
    "francais": "français", "francaise": "française",
    "facon": "façon", "facons": "façons",
    "arrange": "arrangé", "arrangee": "arrangée",
    "deroule": "déroule", "derouler": "dérouler",
    "etaye": "étayé", "etayee": "étayée",
    "numerote": "numéroté", "numerotee": "numérotée",
    "reguliere": "régulière", "regularite": "régularité",
    "repartit": "répartit",
    "resolution": "résolution", "resolutions": "résolutions",
    "securise": "sécurise",
    "sequence": "séquence", "sequences": "séquences",
    "tranchee": "tranchée",
    "unitaire": "unitaire",
    "veritable": "véritable", "veritablement": "véritablement",
    "zerо": "zéro", "zero": "zéro", "zeros": "zéros",
    "periodicite": "périodicité",
    "generalement": "généralement", "generation": "génération",
    "hierarchie": "hiérarchie",
    "materiau": "matériau", "materiaux": "matériaux",
    "numerique": "numérique", "numeriques": "numériques",
    "operateur": "opérateur",
    "preambule": "préambule",
    "procedure": "procédure", "procedures": "procédures",
    "reciproque": "réciproque",
    "referentiel": "référentiel",
    "regularise": "régularise",
    "synthese": "synthèse", "syntheses": "synthèses",
    "tres": "très",
    "modere": "modéré", "moderee": "modérée",
    "eleves": "élevés", "elevees": "élevées",
    "attenue": "atténue", "attenuer": "atténuer",
    "cede": "cède", "ceder": "céder",
    "degre": "degré", "degres": "degrés",
    "delai": "délai", "delais": "délais",
    "densites": "densités",
    "depense": "dépense", "depenses": "dépenses",
    "detaille": "détaillé", "detaillee": "détaillée",
    "ecoule": "écoulé", "ecoulee": "écoulée", "ecoulement": "écoulement",
    "etalement": "étalement",
    "evolue": "évolue", "evoluer": "évoluer", "evolution": "évolution",
    "excede": "excède", "exceder": "excéder",
    "frequences": "fréquences",
    "identifie": "identifie", "identifier": "identifier",
    "inference": "inférence",
    "intervalle": "intervalle", "intervalles": "intervalles",
    "irregulier": "irrégulier", "irreguliere": "irrégulière",
    "lisibles": "lisibles",
    "materiel": "matériel",
    "modelise": "modélise", "modeliser": "modéliser",
    "penible": "pénible",
    "periodique": "périodique",
    "prealable": "préalable",
    "precaution": "précaution", "precautions": "précautions",
    "predefini": "prédéfini",
    "preferable": "préférable",
    "premisse": "prémisse", "premisses": "prémisses",
    "reguliers": "réguliers",
    "relevement": "relèvement",
    "renouvelle": "renouvelle",
    "repartis": "répartis",
    "reperer": "repérer",
    "requiert": "requiert",
    "residuel": "résiduel",
    "retabli": "rétabli",
    "revision": "révision",
    "selectionner": "sélectionner", "selectionnee": "sélectionnée",
    "separe": "sépare", "separer": "séparer", "separation": "séparation",
    "severement": "sévèrement",
    "specifie": "spécifie", "specifier": "spécifier",
    "suggere": "suggère", "suggerer": "suggérer",
    "superieur": "supérieur", "superieure": "supérieure", "superieurs": "supérieurs",
    "inferieur": "inférieur", "inferieure": "inférieure", "inferieurs": "inférieurs",
    "temoin": "témoin", "temoins": "témoins",
    "tolerance": "tolérance", "tolere": "tolère",
    "transfere": "transfère", "transferer": "transférer",
    "ulterieur": "ultérieur", "ulterieure": "ultérieure",

    # --- dernier releve sur le texte visible des pages ---
    "avancant": "avançant", "commencant": "commençant", "placant": "plaçant",
    "bornee": "bornée", "bornees": "bornées", "bornes": "bornés",
    "compare": "comparé", "comparee": "comparée", "compares": "comparés",
    "comparees": "comparées",
    "depot": "dépôt", "depots": "dépôts",
    "l'etait": "l'était",
    "simule": "simulé",
    "teste": "testé",
    "tire": "tiré", "tiree": "tirée", "tirees": "tirées", "tires": "tirés",
    "affiches": "affichés", "affichees": "affichées", "affichee": "affichée",
    "achete": "acheté",
        "fige": "figé",
        "designe": "désigné", "designait": "désignait", "designer": "désigner",
        "vise": "visé",
    "trouve": "trouvé",
    "releve": "relevé",
                                                            "reperage": "repérage",
    "artefact": "artefact",
    "queues": "queues",
}
